# CellBin2.0 contrib, AGPL-3.0 license
# ssDNA=1, DAPI=2, HE=3, IF=4, Transcriptomics=5, Protein=6, UNKNOWN=10

trackPoints:
  detect_channel: -1 # 若输入图为3通道，需指明检测通道。否则，程序会自动转为单通道图
  first_level_thr: 5  # [th  # th2) -> track_point_score = 1
  second_level_thr: 20  # [th2  # inf) -> track_point_score = 2
  good_thresh: 5  # 大于该阈值的被计数为good_fov
  process: 10  # 点检测推理进程数设置"
  conf_filter: 0.5  # 依据此数值对检测结果进行置信度过滤，若值小于0就不做过滤")  # 全局模板设置只要0.5以上的点
  high_freq_angle_thr: 0.05  # 
  DEFAULT_STAIN_TYPE: 1  # ssDNA染色
  SUPPORTED_STAIN_TYPE: [1, 2, 3]  # ssDAN染色, DAPI染色，HE染色
  ssDNA_weights_path: points_detect_yolov5obb_SSDNA_20220513_pytorch.onnx  # ssDNA染色图对应的权重文件名
  DAPI_weights_path: points_detect_yolov5obb_SSDNA_20220513_pytorch.onnx  # DAPI染色图对应的权重文件名
  HE_weights_path: points_detect_yolov5obb_SSDNA_20220513_pytorch.onnx  # HE染色图对应的权重文件名
  IF_weights_path: points_detect_yolov5obb_SSDNA_20220513_pytorch.onnx  # IF染色图对应的权重文件名
  GPU: 0  # 推理使用的GPU编号
  num_threads: 0  # 推理使用的线程数

clarity:
  GPU: 0  # 推理使用的GPU编号
  num_threads: 0  # 推理使用的线程数
#  DEFAULT_STAIN_TYPE: 1  # ssDNA染色
#  SUPPORTED_STAIN_TYPE: [1, 2]  # ssDAN染色, DAPI染色
  ssDNA_weights_path: clarity_eval_mobilev3small05064_DAPI_20230608_pytorch.onnx  # ssDNA染色图对应的权重文件名
  DAPI_weights_path: clarity_eval_mobilev3small05064_DAPI_20230608_pytorch.onnx  # DAPI染色图对应的权重文件名
  #  thr: 0.85
  #  cluster_area_thr: 0.05
  #  cluster_width_thr: 0.2
  #  cluster_height_thr: 0.2
  #  batch_size: 2000

trackLines:
  score_thr: 0
  topk: 10

chipDetector:
  detect_channel: -1
  score_thr: 0.1  # 得分阈值
  stage1_weights_path: chip_detect_obb8n_640_SD_202409_pytorch.onnx
  stage2_weights_path: chip_detect_yolo8x_1024_SDH_stage2_202410_pytorch.onnx
  GPU: 0
  num_threads: 0

templateReferenceV1:
  pair_points_thr: 10
  pair_points_qc_thr: 5
  range_image_size_thr: 5000
  pair_correct_thr: 20
  cluster_num_thr: 10

templateReferenceV2:
  v2_ssDNA_pass_thr: 0.1
  v2_HE_pass_thr: 0.01
  v2_scale_range_thr: [0.3, 1.7]
  v2_rotate_range_thr: 35
  v2_search_range_thr: 500
  v2_rotate_fov_min_thr: 7

tissueSegmentation:
  ssDNA_weights_path: tissueseg_bcdu_S_240618_tf.onnx
  DAPI_weights_path: tissueseg_bcdu_SDI_230523_tf.onnx
  HE_weights_path: tissueseg_bcdu_H_20241018_tf.onnx
  IF_weights_path:
  Transcriptomics_weights_path: tissueseg_bcdu_rna_220909_tf.onnx
  Protein_weights_path: tissueseg_bcdu_rna_220909_tf.onnx
  GPU: 0
  num_threads: 0

cellSegmentation:
  ssDNA_weights_path: cellseg_bcdu_SHDI_221008_tf.onnx
  DAPI_weights_path: cellseg_bcdu_SHDI_221008_tf.onnx
  HE_weights_path: cellseg_bcdu_H_240823_tf.onnx
  IF_weights_path: cyto2torch_0
  Transcriptomics_weights_path: cellseg_unet_RNA_20230606.onnx
  Protein_weights_path: cellseg_unet_RNA_20230606.onnx
  GPU: 0
  num_threads: 0

Registration:
  HE_channel: 1

cellCorrect:
  expand_r: 10
  process: 30

calibration:
  offset_thr: 20

defaultImage:
  clarity: false

